- &apps
  - !host 560732129735/blueOrchidApplication

- &secrets
  - !variable githubUsername
  - !variable githubPassword
  - !variable dbUrl
  - !variable dbUsername
  - !variable dbPassword

- !group secrets

- !permit
  role: !group secrets
  resources: *secrets
  privileges: [ read, update, execute ]

- !grant
  roles:
  - !group secrets
  - !group iam-authn
  members: *apps