# policy id needs to match the convention `conjur/authn-iam/<service ID>`
- !policy
  id: conjur/authn-iam/dev
  body:
  - !webservice
  - !group clients
  - !permit
    role: !group clients
    privilege: [ read, authenticate ]
    resource: !webservice

- !policy
  id: blueOrchidApplication
  body:
  - !group iam-authn

- !grant
  role: !group conjur/authn-iam/dev/clients
  member: !group blueOrchidApplication/iam-authn