- !policy
  id: secretApp
  body:
    - &variables
      - !variable connectionstring

# Create a group that will have permission to retrieve variables
    - !group secrets-users

# Give the group permission to retrieve variables
    - !permit
      role: !group secrets-users
      privilege: [ read, execute ]
      resource: *variables

# Create a layer to hold this application's hosts
    - !layer

# The host ID needs to match the AWS ARN of the role we wish to authenticate.
    - !host 560732129735/TrustedWithSecret

# Add our host into our layer
    - !grant
      role: !layer
      member: !host 560732129735/TrustedWithSecret

# Give the host in our layer permission to retrieve variables
    - !grant
      member: !layer
      role: !group secrets-users