- !policy
  id: BotApp
  body:
    # Define a human user, a non-human identity that represents an application, and a secret
  - !user jim
  - !host blueOrchidApplication
  - !variable secretVar
  - !permit
    # Give permissions to the human user to update the secret and fetch the secret.
    role: !user jim
    privileges: [read, update, execute]
    resource: !variable secretVar
  - !permit
    # Give permissions to the non-human identity to fetch the secret.
    role: !host blueOrchidApplication
    privileges: [read, execute]
    resource: !variable secretVar
